version: "3.0"

networks:
  database:
    external: true

services:
  ncu-mrbs:
    image: tommygood/ncu-mrbs:latest
    ports:
      - 3000:3000
    environment:
      - db_host=mysql
      - db_name=2fconference
      - db_port=3306
      - db_username=2fconference
      - db_password=Po2fF8MoFUnPbHLmNM8aNilNydqgY9oSbrWLEdZJogeuU2RbtH
      - host=${HOST}
      - oauth_client_id=${OAuth_Client_ID}
      - oauth_client_secret=${OAuth_Client_Secret}

    # make sure the network 'database' existed
    #networks:
      #- database